service: lambda-spring-cloud
provider:
  name: aws
  runtime: java8
  timeout: 300
package:
  artifact: target/spring-cloud-functions-aws-maven-0.0.1-SNAPSHOT.jar
functions:
  uppercase:
    handler: com.prashanth.spring.cloud.aws.SpringBootLambdaHandler
    environment:
      FUNCTION_NAME: uppercase
